### PR TITLE
Css modifications

### PR DESCRIPTION
**Pull request by AdrianBor**
Changement of Card detail and small things

### CODE REVIEW

**Comment by lukaswelte** [comment]
@AdrianBor the build fails because `img/map-star-added.svg` can't be found. Make sure it is in there or remove the reference in the css

**Comment by AdrianBor** [comment]
Ok I commit it.

**Comment by lukaswelte** [comment]
@AdrianBor is this still valid or should this be deleted?

**Comment by AdrianBor** [comment]
@lukaswelte Yes this branch is still valid and could overlaps others but this one is full valid.

**Comment by lukaswelte** [comment]
Ok than this needs to be updated and like mentioned the start svg has to be added.
And right now the conflicts in the 3 conflicting files have to be resolved.

**Comment by AdrianBor** [comment]
@lukaswelte I changed the file and resolved the conflicts (normally).

**Review by lukaswelte — CHANGES_REQUESTED** [review]
@AdrianBor The image `7617A72D280F7FDB.jpg` is not used anywhere. So just remove it.
Or am I just not seeing where it is referenced?

**Review by AdrianBor — COMMENTED** [review]
@lukaswelte Modifications done.

**Review by lukaswelte — APPROVED** [review]

**Pull request merged**
