### PR TITLE
Trip Detail Page Template

### PR DESCRIPTION
**Pull request by AdrianBor**

### CODE REVIEW

**Comment by lukaswelte** [comment]
This seems like Work in Progress so I prefixed the title with `[WIP]`.
If it is not just remove the WIP from the title again and leave me a comment that I should look into it ;)

But what I see right now already looks great! 👍

**Comment by AdrianBor** [comment]
Yes you are right i need a bit more time for that one. Will finish it by today.

**Comment by AdrianBor** [comment]
@lukaswelte new pull request available, status is done :)

**Review by lukaswelte — APPROVED** [review]

**Comment by lukaswelte** [comment]
Looks nice 👍

**Pull request merged**
