### PR TITLE
Labelling of Event

### PR DESCRIPTION
**Pull request by AdrianBor**
This arrive normally when we recenter the map. But it Doesn’t work always. Could fix it?

### CODE REVIEW

**Comment by lukaswelte** [comment]
Sorry I don't get what is wrong. 
Could you explain more detailed maybe with an image or just more text what you want to have differently, @AdrianBor?

**Comment by AdrianBor** [comment]
Everything is fine on that branch, we can merge it. The only issue is regarding the user positionment. I notced that the first time I press the favorite button, my map recenter on the user, which is great BUT it doesn't work automatically after, after it's a positioning of my center map. Do you see the difference? Do you have the same problem? It's not related to that branch, but I noticed that during that modification. @lukaswelte

**Comment by lukaswelte** [comment]
When you press the star button right now it does not center on the user's location. It just creates a dot where the user is. I create #37 for this.

**Review by lukaswelte — COMMENTED** [review]
Is this really something you want to merge as the form capability is removed here and #34 uses it to add a new favorite spot marker @AdrianBor?

**Comment by AdrianBor** [comment]
@lukaswelte As we said it's just a map marker, but we could also add just a line to just tell what is it about. I agree with that it's weird to remove it. I Will add it. Could we merge for now and add it on a new one ?

**Comment by lukaswelte** [comment]
@AdrianBor I would rather merge #34 as it has that one line description and then change the style a little again. Or don't you think that a little desc would be helpful to the user?

**Review by AdrianBor — COMMENTED** [review]
Again you are right @lukaswelte let's do it in that way. we merge that version, the restyling will follow after, we keep the version with the form :)

**Comment by lukaswelte** [comment]
So then I'll close this pull request as the restyling will look different anyway.

**Pull request closed without merging**
