### PR TITLE
Fix redirection after login

### PR DESCRIPTION
**Pull request by lukaswelte**
The redirect after the login should now work correctly again

### CODE REVIEW

**Review by AdrianBor — APPROVED** [review]
Working! congratz

**Comment by lukaswelte** [comment]
It is working for you? 
Which browser did you test it in?

**Comment by AdrianBor** [comment]
safari

**Comment by lukaswelte** [comment]
Thanks. Could you also try in chrome in addtition?

**Comment by AdrianBor** [comment]
I can't i m on the go now for an hour, will let you know after.

**Comment by AdrianBor** [comment]
Ok @lukaswelte doesn't work on Chrome...

**Pull request merged**
