### PR TITLE
AddMark Page new Design

### PR DESCRIPTION
**Pull request by AdrianBor**

### CODE REVIEW

**Comment by lukaswelte** [comment]
Is this supposed to be ready for merge @AdrianBor?

**Comment by AdrianBor** [comment]
No Yet, It's in progress, I just put the placeholder I'm still working on.

**Comment by lukaswelte** [comment]
Alright then I'll put it on WIP

**Comment by AdrianBor** [comment]
Ready to be merged for me @lukaswelte

**Comment by lukaswelte** [comment]
Not really.. the character count is missing and the second input for the location title is missing @AdrianBor

**Comment by AdrianBor** [comment]
ok @lukaswelte .

I added the elements, I'm confronted to coding problems. 

Counter: I want him to appear WHEN we start writing.
Localisation: I want him to appear WHEN we start writing too. 

Is it possible  ? I tried to implement it with the autoresize but I failed...

**Comment by lukaswelte** [comment]
I like it. Could you put up an issue for that (or trello card) so that we don't forget, but I'll do this when I integrate it and make it functional. As this requires to have controlled input elements and I need to make them controlled for it to integrate it with the backend I'll do this in the same step and make it functional, agree?

**Comment by AdrianBor** [comment]
@lukaswelte ok for me! You can merge when you want.

**Review by lukaswelte — APPROVED** [review]

**Pull request merged**
